Lambda-School-Labs/artificial-artist-fe

package.json, src/App.js, src/components/CreateVideo.js, src/components/Loading.js, src/components/Login.js, src/components/PrivateRoute.js, src/components/Signup.js, src/components/VideoList.js, src/components/VideoPage.js, src/index.js, src/store/actions/index.js, src/store/reducers/index.js, src/utils/axiosWithAuth.js, yarn.lock
Built out a bit of a boilerplate that includes the following components in various states:
- Login
- Signup
- Loading
- CreateVideo
- VideoList
- VideoPage
The following actions:
- Login
- Signup
- Get Videos
- Logout
It also sets up basic authenticated routes, which we can play around with. 
=> Boilerplate for Redux/Actions/Reducers/Components

package.json, src/App.js, src/components/Navigation.js, src/index.css, yarn.lock
Navigation feature
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] Complete, but not tested (may need new tests)
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] My changes generate no new warnings
- [ X ] There are no merge conflicts
=> Created and styled the navbar

.gitignore, package.json, src/components/Signup.js, src/store/actions/index.js, yarn.lock
- Added a bunch of fields for signup
- Adjusted the signup/login actions to actually work
- Fixed URL for server so that it will work on a cross-env basis
=> Made login and signup functional locally

src/components/Navigation.test.js, src/utils/renderWithReduxAndRouter.js
=> created a test for the navbar

src/App.js, src/store/actions/index.js, yarn.lock
I ran into a few issues after merging some things together. We'll want to discuss these tomorrow.
I tested this manually locally.
- Issues with going to the CreateVideo route due to it comparing things in a way it didn't like. 
- Issues with 'creds' not being defined when doing POSTs to the backend on that action
=> Fixed some errors that came out of multiple merges

src/store/actions/index.js
Fixes an issue where now we're building the baseUrl inside of axiosWithAuth instead of defining urlServer inside of the actions file. 
- Tested locally against backend
=> Fix for url server being undefined, it's now handled in axiosWithAuth

src/components/CreateVideo.js
Added a couple of useState functions to set up conditional rendering of some stuff on this page.  I have a "Selected Song" portion of the page that will render when a song is clicked.  The submit button will also only render when a song is selected and a title is entered.
Conditional rendering
I tested it by running it locally.  I tried a half dozen ways to break it and it seems to work well.  Haven't written any unit tests though.
=> Create video page

src/App.js, src/components/SingleVideoPage.js, src/store/actions/index.js, src/store/reducers/index.js
Single video page renders in the console and shows no merging errors
- [x ] Console rendering
=> Single vid

src/store/actions/index.js, src/store/reducers/index.js
Fixed the bug to route to single video after creating one
=> fixed the routing issue after creating a new video

.codeclimate.yml, .github/workflows/ci.yml, .gitignore, package.json, src/App.test.js, yarn.lock
Setting up code climate files again, looking to correct the ? on test coverage.
Fixes - test coverage blank
- [x ] I have performed a self-review of my own code
=> setting up code climate again, fixing test coverage

src/components/SingleVideoPage.js
Single vid page code updated to add thumbnail, video rendering, artist name, song and video title
=> cleanup request - only single vid

src/components/SingleVideoPage.js, src/components/VideoList.js, src/store/actions/index.js
Updated the single video page to account for video_status on the backend. Also updated how the front-page calls 9 random videos. We'll need to make more modifications here as we refactor.
=> Video Status Changes

.prettierrc
Added a prettier config so we can resolve all these weird issues between MacOS and Windows. 
```
{
"trailingComma": "es5",
"tabWidth": 2,
"semi": true,
"singleQuote": false,
"bracketSpacing": true,
"arrowParens": "always"
}
```
=> Added prettier config

src/components/SearchVideos.js
Functioning video search page - click result takes user to just video
- [x ] Complete, tested, ready to review and merge
- [x ] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] My changes generate no new warnings
- [x ] There are no merge conflicts
=> Video browse

src/App.js, src/components/Login.js, src/components/Signup.js, src/index.css
Added styling for login/signup form
=> Signup & Login styling

src/components/CreateVideo.js
Added and advanced options button that allows the users to set the parameters that would customize their videos.  Utilized dropdown menus and slider input fields.  
Fixes # 
This feature allows the users to customize their videos.
Added feature
=> Ds parameters

src/components/UserPage.js, src/components/Video.js
Fixed ternary issue on the Profile Page to return a create video prompt for new users, and fixed 'Key' warning from the console. Also changed the naming convention for fileConfig to remove the Error that was appearing from the Video component.
=> Warnings errors

src/components/CreateVideo.js, src/components/UserPage.js, src/store/actions/index.js
Styling for creation page
Also fixed bugs with video creation and history push
=> Styling and Bug Fixes

src/components/UserPage.js, src/components/Video.js, src/components/VideoList.js
Made the styles a bit smaller for big and small videos. Also adjusted profile page to be way better.
=> Styling fixes to make things a bit more legible

package.json, src/App.js, src/components/Navigation.js, src/middleware/TokenChecker.js, src/store/actions/index.js, yarn.lock
Created a Token check to verify if a token is or is not expired and set the profile page to a private route if the user is not logged in.
**User has no token**
**User has a token/token is valid**
**User token has expired and can no longer access the profile page (re-routed to login)**
=> Expired token

src/components/SearchVideos.js, src/store/actions/index.js, src/store/reducers/index.js
Fine tuning the way the search shows up
Fixes # (issue) 
- [x ] Complete, but not tested (may need new tests)
- [x ] Test A
- [x ] I have performed a self-review of my own code
- [x ] There are no merge conflicts
=> refining the video search, added action for find videos

package.json, src/App.js, yarn.lock
Added tag manager handler so that we can track things
=> Added google tag manager for google analytics

src/components/UserPage.js
Re-added the falsy portion of the `props.userVideos` to show the new User prompt and added styling 
=> Profile page

src/components/CreateVideo.js, src/components/Footer.js, src/components/Login.js, src/components/Navigation.js, src/components/SecondaryNav.js, src/components/Signup.js, src/components/SingleVideoPage.js, src/components/UserPage.js, src/components/Video.js, src/components/VideoList.js
Added a bunch of subtle animations, added the branding to the single video page, and added a footer giving us credit on the home and profile page (doesn't fit elsewhere tbh).
=> Added a bunch of subtle effects and a footer giving us credit
